import { useState } from "react";
import { css } from "@emotion/react";
import styled from "@emotion/styled";
import Head from "next/head";

import Input from "../components/Input";
import Output from "../components/Output";
import Logo from "../components/Logo";
import Footer from "../components/Footer";

const Wrapper = styled.section(
  ({ theme }) => css`
    padding: 2rem;
    display: flex;
    flex-direction: column;

    ${theme.breakpoints[1]} {
      flex-direction: row;
      justify-content: space-evenly;
      max-width: 1280px;
      margin: auto;
    }
  `
);

export default function Home() {
  const [wordToSpell, setWordToSpell] = useState("");

  return (
    <div>
      <Head>
        <title>Spelling</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Logo />

      <Wrapper>
        <Input handleChange={setWordToSpell} wordToSpell={wordToSpell} />

        <Output wordToSpell={wordToSpell} />
      </Wrapper>
      <Footer />
    </div>
  );
}
