import { useState } from "react";
import { css } from "@emotion/react";
import styled from "@emotion/styled";
import Head from "next/head";

import Input from "../components/Input";
import Output from "../components/Output";
import Logo from "../components/Logo";

const Wrapper = styled.section(
  () => css`
    padding: 2rem;
  `
);

export default function Home() {
  const [wordToSpell, setWordToSpell] = useState("");

  return (
    <div>
      <Head>
        <title>Spelling</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Logo />

      <Wrapper>
        <Input handleChange={setWordToSpell} wordToSpell={wordToSpell} />

        <Output wordToSpell={wordToSpell} />
      </Wrapper>
    </div>
  );
}
